# Minimal, single-line; Catppuccin Mocha; simple git & truncated path
format = "$directory$status"
right_format = "$git_branch$git_status$azure$kubernetes$docker_context"
add_newline = false

# Palette (Catppuccin Mocha)
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext0  = "#a6adc8"
overlay0  = "#6c7086"
surface0  = "#313244"
base      = "#1e1e2e"

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vicmd_symbol   = "[❮](sapphire)"
format = "$symbol "

[directory]
truncation_length = 3
truncate_to_repo = true
read_only = " "
style = "bold text"
repo_root_style = "bold mauve"
fish_style_pwd_dir_length = 0
format = "[$path]($style) "

[git_branch]
symbol = ""
format = "[ $symbol$branch ](blue)"
truncation_length = 20
truncation_symbol = "…"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "subtext0"
conflicted = ""
staged = ""
modified = ""
untracked = ""
stashed = ""
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${ahead_count}⇣${behind_count}"
up_to_date = ""
renamed = ""
deleted = ""

# Performance-oriented tweaks for big repos
[git_metrics]
disabled = true
[git_commit]
only_detached = true
[git_state]
disabled = false

[cmd_duration]
min_time = 3000
format = "[⏱ $duration]($style)"
style = "yellow"

[status]
disabled = false
format = "[ $status]($style) "
style = "red"
recognize_signal_code = true
map_symbol = true
pipestatus = false
success_symbol = ""

[azure]
disabled = false
format = "[ $subscription]($style)"
style = "mauve"

[kubernetes]
disabled = false
format = "[⎈ $context(::$namespace)]($style)"
style = "teal"
contexts = [ { context_pattern = ".*", style = "teal" } ]
detect_extensions = ["yaml", "yml", "json", "helm"]
detect_files = ["k8s", "kustomization.yaml", "Chart.yaml"]

[docker_context]
disabled = false
symbol = " "
format = "[$symbol$context]($style)"
style = "sky"

[python]
disabled = false
format = "[ $virtualenv]($style)"
style = "green"
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "poetry.lock", "Pipfile", "requirements.txt", ".python-version"]
pyenv_version_name = false

[nodejs]
disabled = true
[rust]
disabled = true
[golang]
disabled = true

[time]
disabled = false
time_format = "%H:%M"
format = "[ $time]($style)"
style = "overlay0"
